### ISSUE TITLE
현재 지원 브라우저의 범위가 어디까지인가요?

### ISSUE THREAD

**Issue by ioz2014** [izuzero/xe-module-ajaxboard#18]
모바일, PC를 포함해서 지원 브라우저와 버전이 무엇인지 밝혀주시는 것도 좋을 것 같습니다^^

**Comment by izuzero** [comment]
웹소켓은 딱히 지원 범위가 제공되지 않고, SSE는 [이 문서](https://github.com/Yaffle/EventSource/)에서 설명하는 대로 지원합니다.
HTML5 알림 플러그인은 [이 문서](http://caniuse.com/#feat=notifications)에서 설명하는 대로 지원합니다.

**Comment by ioz2014** [comment]
IE는 역시 해당없음이군요. 답변 정말 고맙습니다^^

**Comment by wookho** [comment]
@ioz2014 SSE는 IE11 지원이 되는 것 같네요. 저희 사이트에서 해 보니 IE11에서도 새로고침 없이 페이지이동이 잘 됩니다.

**Comment by izuzero** [comment]
@wookho
polyfill 라이브러리를 사용하고 있기 때문에 IE8 이상 지원입니다.

**Comment by wookho** [comment]
@izuzero 네. @ioz2014 님께서 IE는 모두 안되는 것으로 알고 계신거 같아서 적어드렸어요.

**Comment by izuzero** [comment]
@wookho
HTML5 알림 플러그인은 IE 해당 없음이기에 전 그렇게 알아들었네요 :) 이분이 제대로 알아가셨깅 바라며..
