### ISSUE TITLE
로딩 메시지 사용함으로 설정했음에도 XE 기본 로딩메시지가 뜨지 않음

### ISSUE THREAD

**Issue by ioz2014** [izuzero/xe-module-ajaxboard#19]
로딩 메시지를 사용하는 것으로 설정했는데도 xe의 기본 AJAX 통신 메시지가 뜨지 않습니다.
댓글 작성시 DEFAULT 게시판에서 테스트했습니다.

CPAGE 이동이나 댓글 삭제시에도 새로고침이 되는 것이 약간 아쉬운 점입니다.

**Comment by izuzero** [comment]
cpage 이동이나 댓글 삭제 시 새로고침이 되지 않고 바로 처리되게 만들어져 있습니다.
해당 주소를 남겨주시면 확인해보겠습니다.
로딩 메시지는 가장 마지막에 로딩되는 플러그인의 설정을 따라갑니다.

**Comment by ioz2014** [comment]
정정합니다. cpage 이동시에는 새로고침이 되지 않지만 삭제시에는 페이지가 넘어갑니다.
http://php.raonnet.com/index.php?mid=test&document_srl=170

**Comment by ioz2014** [comment]
플러그인 로딩에 대해 우선순위를 설정할 수 있나요? 만약 그렇지 못하다면 차라리 통신메시지 설정은 모듈의 전체 설정에 넣는것이 좋아보입니다.

**Comment by izuzero** [comment]
통신 메시지 설정은 모듈 설정에서 조작할 수 있도록 처리하겠습니다.

**Comment by ioz2014** [comment]
감사합니다^^

**Comment by izuzero** [comment]
fixed 885bae7
