### ISSUE TITLE
게시글 및 댓글 삭제 시 새로고침이 되는 문제

### ISSUE THREAD

**Issue by izuzero** [izuzero/xe-module-ajaxboard#20]
기본 게시판 대응 플러그인 #19

**Comment by ioz2014** [comment]
원래는 게시글 삭제시에도 페이지 이동이 방지되는 거였나요?! 그건 몰랐습니다.
여담으로 삭제 버튼을 누르면 경고창으로 YES  NO를 물었으면 좋겠습니다. 바로 삭제되면 실수로 인한 불상사가 많을 것 같네요.

**Comment by izuzero** [comment]
fixed ec819b9
