### ISSUE TITLE
댓글 갱신 시 textarea의 내용도 사라지는 문제

### ISSUE THREAD

**Issue by ioz2014** [izuzero/xe-module-ajaxboard#22]
새 댓글이 확인되어 댓글 부분이 갱신될 때, textarea의 내용도 없어지는 문제가 있습니다.

작성중인 댓글이 날아가게 되는 것인데 개선이 필요하다고 생각합니다.

테스트: 스케치북

아마 다른 스킨도 동일한 문제가 있지 않나 예상합니다.

**Comment by ioz2014** [comment]
그리고 https://github.com/izuzero/xe-module-ajaxboard-plugins/releases/tag/1.0.1 여기에 들어가면 404 페이지가 나오네요.

**Comment by izuzero** [comment]
없는 페이지인데 접속 시도하니 404 페이지가 뜨죠...
[이 주소](https://github.com/izuzero/xe-module-ajaxboard-plugins/releases)가 맞는 주소입니다.
어느 textarea가 사라진다는 건지 정확하게 말씀해주시지 않으면 모릅니다.

**Comment by ioz2014** [comment]
제 알림에 뜬 주소가 잘못되었나보네요;;

댓글 내용입력창입니다. 글쓴이 비밀번호같은 input의 내용은 사라지지 않고 그대로 있습니다.

**Comment by izuzero** [comment]
"본인이" 댓글을 작성했을 경우 "댓글을 작성한 창만" 에디터 내용을 비우는 루틴이 있습니다. 잘못된 처리가 아닙니다.

**Comment by izuzero** [comment]
스케치북 게시판은 completeInsertComment 함수에서 ajaxboard.clearEditor 함수를 실행합니다. /tpl/js/client.js 파일을 확인하세요.

**Comment by ioz2014** [comment]
예, 그건 알고 있습니다. 다만 새 창을 띄워놓고 댓글입력란에 입력을 한뒤, 또 다른 창에서 댓글 등록을 하는 식으로 테스트를 해보니까 새 창의 댓글 입력란도 초기화되기에 이슈등록을 한것입니다.

즉, 본인이 댓글을 작성한 경우에 모든 창에서 에디터 내용이 비워지는 문제가 있습니다. 타인이 작성한 댓글을 불러올때도 이런 문제가 생기는지는 테스트하지 않았습니다. 하지만 이 부분도 재검토 부탁드립니다.

**Comment by izuzero** [comment]
기본 게시판에서는 재현되지 않습니다. 그러나 스케치북 게시판에서는 말씀하신 증상이 나타나고 있는 걸 확인했습니다.
왜 이런지는 자세히 봐야겠지만, 이 이슈는 닫겠습니다. 플러그인 저장소에 새로 이슈를 남겨주세요.
