### ISSUE TITLE
Ajax 발음과 관련된 문의

### ISSUE THREAD

**Issue by wonsuc** [izuzero/xe-module-ajaxboard#30]
안녕하세요. 일단 훌륭한 모듈을 제작하신거 진심으로 대단하다고 생각합니다.

뭐, 어차피 이름을 이렇게 지으셨으니 별 수 없으시겠지만 Ajax 발음에 대해서 약간 특이한(?) 발음법을 사용하시는 것 같아 문의 드립니다.

외국이나 한국이나 Ajax를 어떻게 발음 하냐에 대한 논의가 많이 되어왔는데 어느정도 표준이 잡힌지 오래되었습니다.

일단, 외국 같은 경우는 "Ay-Jacks"로 거의 굳혀진 상태이고, 한국식으로 발음하면 "에이젝스" 혹은, "에이잭스"으로 발음됩니다.

한국의 경우는 거의 "에이젝스"로 굳혀진 걸로 알고 있는데 제가 알기론 "아약스"라고 표기하시는 분이 매우 생소한 걸로 압니다.

다른 용어일 경우에 "아약스"를 쓰는건 바른 발음법일 수 있는데 프로그래밍 용어인 Ajax는 말 그대 asynchronous JavaScript and XML의 약어로서의 또 다른 단어이기 때문에 기존에 존재하는 Ajax라는 단어와 혼동해서 발음해서는 안된다고 생각하고 있습니다.

뭐, 어차피 외래어라 한국어로 이렇게 부르나 저렇게 부르나 상관은 없지만 프로그래밍에서 용어의 통일도 굉장히 중요한 이슈로 자리잡고 있기 때문에 한번쯤 고민 해보셨으면 하는 차원에서 이슈를 남겨봅니다.

출처: 
http://www.faqoverflow.com/english/11270.html
https://kldp.org/node/68455

**Comment by izuzero** [comment]
모듈 만들 때 발음 나는 대로 이름을 짓다 보니 이렇게 됐습니다.
이제 와서 고칠 순 없겠지요 :)
