### ISSUE TITLE
페이지뷰가 지속적으로 올라갑니다. 

### ISSUE THREAD

**Issue by allcalc** [izuzero/xe-module-ajaxboard#32]
https://www.xpressengine.com/qna/22922896
관련 글입니다. 

![image](https://cloud.githubusercontent.com/assets/10527959/5813559/e03d5f02-a0c2-11e4-85b0-b1f68bd89efc.png)

우분투 14.04 + NGINX + MariaDB + PHP-fpm 환경입니다.
사이트 운영한지 얼마 되지 않았고, 
아약스보드 모듈은 기록을 보니 1주일 전인 1월 12일 오후에 설치하였습니다. 

첨에 잘 안돼서 애먹었던 기억이 있구요. 몇시간 잡고 씨름해서 겨우 동작이 되었고, 
이후 며칠간 스케치북 게시판 플러그인 문제로 또 씨름을 하였습니다. 

그런데 설치 이후에 사이트 페이지뷰 수가 비정상적으로 높은 상황이 계속되었습니다. 
첨에는 원인을 몰랐는데, 오늘에서야 아약스보드 때문이라는 것을 알게 되었습니다. 

모듈 쪽을 손봐야 할지, 
아니면 서버에 설치한 node.js 나 forever 로 실행한 것(list 에 안보이던데...) 등을 손봐야할지 
잘 모르겠습니다.  
- 기본 카운터, 확장 카운터 번갈아가며 테스트 해봤지만, 둘다 똑같습니다.

**Comment by izuzero** [comment]
SSE를 통해 서버에 연결되고 있는 것 같습니다. forever list에 웹소켓 서버가 뜨지 않는다는 이야기는 서버가 켜지지 않았다는 뜻이고, 클라이언트에서는 웹소켓에 연결할 수 없으니 자동으로 SSE로 전환되는 것입니다.
SSE는 지정한 시간초마다 서버에 계속 연결했다 끊었다 하는 폴링 방식입니다. 따라서 이러한 방식은 소규모 사이트거나 웹호스팅으로 인해 웹소켓 서버를 구성할 수 없는 환경에 적합하며, 페이지뷰가 높게 나타날 수 있습니다.
따라서 웹소켓 서버가 왜 정상적으로 작동하지 않는지 확인해봐야 합니다. 다행히 forever 모듈은 로그 기능을 제공합니다. -a 옵션(기존 로그 파일에 계속해서 로그 추가)과 -l 옵션(이 옵션 다음에 파일 경로를 적으면 지정한 파일 경로에 로그가 기록됨)을 사용해 작동 로그를 기록하세요. 또는 forever start 명령어 대신 node 명령어를 사용하여 콘솔창에 직접 웹소켓 서버를 실행할 수도 있습니다. 그러나 node 명령어는 백그라운드 동작이 힘들기 때문에 로그 확인용으로만 사용하세요.

**Comment by allcalc** [comment]
우왕~~~
딱 말씀하신대로네요. 
forever에 등록하고 나니까 페이지뷰가 잠잠해졌어요. ㅠㅠ

서버 리부팅 하면서 등록된 forever 가 사라졌나봅니다. 
자동으로 시작하게 해둬야겠네요. 

감사합니다. ^^

**Comment by allcalc** [comment]
forever 등록으로 문제는 해결되긴 했는데요. 

이후에도 페이지 방문시에 카운터가 한번에 2개씩 오르는 것 같긴 하네요.
